### ISSUE TITLE
Does not work on latest Rakudo (the code is relying on buggy backtracking)

### ISSUE THREAD

**Issue by AlexDaniel** [jsimonet/dns-zone#5]
Currently the tests are failing (on all rakudos after [963a0f0657a](https://github.com/rakudo/rakudo/commit/963a0f0657abaa0431d465e601c75b50462b4cd2)).

The issue can be “fixed” by adding ``:!r`` here:
https://github.com/jsimonet/dns-zone/blob/master/lib/DNS/Zone/Grammars/Modern.pm6#L252-L260

That being said, I'm not sure why backtracking is needed there. There may be a better way to do it.

See [RT #130117](https://rt.perl.org/Ticket/Display.html?id=130117) for more info.

**Comment by jsimonet** [comment]
Fixed in 186be9599200cc53e864a57344ed026a2893f22a.

Thank you for submitting this PR.

You are saying that I should use || instead of | in the IPV6 regex to match the first one?

**Comment by AlexDaniel** [comment]
No, generally it's not a ``||`` vs ``|`` question. Maybe see [this](https://twitter.com/zoffix/status/921420918471188480) and [this](https://docs.perl6.org/language/regexes#Ratchet).

**Comment by jsimonet** [comment]
I think the backtracking is needed because the first part of an IPV4 can match a IPV6 token (`<h16>`). So I have to test every forms of `<h16> * <ipv4>` before trying to test `<h16>` only one.

Anyway, thank you for the fix 👍
